blank_issues_enabled: true

contact_links:
  - name: ğŸ” Microsoft Security Response Center
    url: https://msrc.microsoft.com/create-report
    about: Please report security vulnerabilities here.
  