# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.1
properties:
  assertions:
    - resource: DeveloperMode
      directives:
        description: Enable Developer Mode
        module: Microsoft.Windows.DSC
      settings:
        Ensure: Present
  resources:
    - resource: WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Community
        module: Microsoft.WinGet.DSC
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget
    - resource: InstallVSConfig
      dependsOn:
        - vsPackage
      directives:
        description: Install required VS workloads
        module: Microsoft.VisualStudio.DSC
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release
        vsconfigFile: .\.vsconfig
  configurationVersion: 0.1.0