# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: vsPackage
      directives:
        description: Install Visual Studio 2022 Community
        module: Microsoft.WinGet.DSC
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudio.2022.Community
        source: winget
    - resource: Microsoft.VisualStudio.DSC/VSComponents
      id: vsConfig
      dependsOn:
        - vsPackage
      directives:
        description: Install required VS workloads
        module: Microsoft.VisualStudio.DSC
        allowPrerelease: true
      settings:
        productId: Microsoft.VisualStudio.Product.Community
        channelId: VisualStudio.17.Release
        includeRecommended: true
        Components:
          - Microsoft.VisualStudio.Workload.NativeGame
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      dependsOn:
        - vsConfig
      directives:
        description: Install Microsoft GDK
        module: Microsoft.WinGet.DSC
        allowPrerelease: true
      settings:
        id: Microsoft.GDK.2303
        source: winget
  configurationVersion: 0.2.0